package main

type TypedMonMovesets struct {
	Type1 string
	Type2 string
	Moves1 [4]string
	Moves2 [4]string //Used to add a secondary moveset
}


var sampleTypeCombos =[]TypedMonMovesets{
	{"Fire", "", [4]string{"Flamethrower", "Scorching_Sands", "Focus_Blast", "Psychic"}, [4]string{"Flare_Blitz", "Stone_Edge", "Earthquake", "Iron_Head"}},
	{"Ice", "", [4]string{"Ice_Beam", "Freeze_Dry", "Focus_Blast", "Shadow_Ball"}, [4]string{"Ice_Spinner", "Earthquake", "Stone_Edge", "Crunch"}},
	{"Ghost", "", [4]string{"Shadow_Ball", "Energy_Ball", "Thunderbolt", "Psychic"}, [4]string{"Poltergeist", "Earthquake", "Stone_Edge", "Thunder_Punch"}},
}

//Need to fill in a second moveset for the full list
// var typeCombos = []TypedMonMovesets{
// 	// Monotypes
// 	{"Normal", "", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Fire", "", [4]string{"Flamethrower", "Scorching_Sands", "Focus_Blast", "Psychic"}, []string{"Flare_Blitz", "Stone_Edge", "Earthquake", "Iron_Head"}},
// 	{"Water", "", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Electric", "", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Grass", "", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Ice", "", [4]string{"Ice_Beam", "Freeze_Dry", "Focus_Blast", "Shadow_Ball"}, []string{"Ice_Spinner", "Earthquake", "Stone_Edge", "Crunch"}},
// 	{"Fighting", "", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Poison", "", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Ground", "", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Flying", "", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Psychic", "", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Bug", "", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Rock", "", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Ghost", "", [4]string{"Shadow_Ball", "Energy_Ball", "Thunderbolt", "Psychic"}, []string{"Poltergeist", "Earthquake", "Stone_Edge", "Thunder_Punch"}},
// 	{"Dragon", "", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Dark", "", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Steel", "", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Fairy", "", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},

// 	// Dual types
// 	{"Normal", "Fire", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Normal", "Water", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Normal", "Electric", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Normal", "Grass", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Normal", "Ice", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Normal", "Fighting", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Normal", "Poison", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Normal", "Ground", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Normal", "Flying", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Normal", "Psychic", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Normal", "Bug", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Normal", "Rock", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Normal", "Ghost", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Normal", "Dragon", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Normal", "Dark", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Normal", "Steel", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Normal", "Fairy", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},

// 	{"Fire", "Water", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Fire", "Electric", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Fire", "Grass", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Fire", "Ice", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Fire", "Fighting", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Fire", "Poison", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Fire", "Ground", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Fire", "Flying", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Fire", "Psychic", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Fire", "Bug", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Fire", "Rock", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Fire", "Ghost", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Fire", "Dragon", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Fire", "Dark", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Fire", "Steel", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Fire", "Fairy", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},

// 	{"Water", "Electric", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Water", "Grass", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Water", "Ice", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Water", "Fighting", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Water", "Poison", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Water", "Ground", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Water", "Flying", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Water", "Psychic", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Water", "Bug", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Water", "Rock", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Water", "Ghost", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Water", "Dragon", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Water", "Dark", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Water", "Steel", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Water", "Fairy", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},

// 	{"Electric", "Grass", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Electric", "Ice", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Electric", "Fighting", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Electric", "Poison", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Electric", "Ground", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Electric", "Flying", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Electric", "Psychic", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Electric", "Bug", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Electric", "Rock", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Electric", "Ghost", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Electric", "Dragon", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Electric", "Dark", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Electric", "Steel", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Electric", "Fairy", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},

// 	{"Grass", "Ice", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Grass", "Fighting", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Grass", "Poison", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Grass", "Ground", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Grass", "Flying", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Grass", "Psychic", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Grass", "Bug", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Grass", "Rock", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Grass", "Ghost", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Grass", "Dragon", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Grass", "Dark", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Grass", "Steel", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Grass", "Fairy", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},

// 	{"Ice", "Fighting", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Ice", "Poison", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Ice", "Ground", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Ice", "Flying", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Ice", "Psychic", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Ice", "Bug", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Ice", "Rock", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Ice", "Ghost", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Ice", "Dragon", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Ice", "Dark", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Ice", "Steel", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Ice", "Fairy", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},

// 	{"Fighting", "Poison", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Fighting", "Ground", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Fighting", "Flying", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Fighting", "Psychic", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Fighting", "Bug", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Fighting", "Rock", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Fighting", "Ghost", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Fighting", "Dragon", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Fighting", "Dark", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Fighting", "Steel", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Fighting", "Fairy", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},

// 	{"Poison", "Ground", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Poison", "Flying", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Poison", "Psychic", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Poison", "Bug", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Poison", "Rock", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Poison", "Ghost", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Poison", "Dragon", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Poison", "Dark", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Poison", "Steel", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Poison", "Fairy", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},

// 	{"Ground", "Flying", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Ground", "Psychic", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Ground", "Bug", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Ground", "Rock", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Ground", "Ghost", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Ground", "Dragon", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Ground", "Dark", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Ground", "Steel", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Ground", "Fairy", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},

// 	{"Flying", "Psychic", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Flying", "Bug", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Flying", "Rock", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Flying", "Ghost", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Flying", "Dragon", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Flying", "Dark", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Flying", "Steel", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Flying", "Fairy", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},

// 	{"Psychic", "Bug", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Psychic", "Rock", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Psychic", "Ghost", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Psychic", "Dragon", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Psychic", "Dark", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Psychic", "Steel", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Psychic", "Fairy", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},

// 	{"Bug", "Rock", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Bug", "Ghost", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Bug", "Dragon", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Bug", "Dark", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Bug", "Steel", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Bug", "Fairy", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},

// 	{"Rock", "Ghost", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Rock", "Dragon", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Rock", "Dark", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Rock", "Steel", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Rock", "Fairy", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},

// 	{"Ghost", "Dragon", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Ghost", "Dark", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Ghost", "Steel", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Ghost", "Fairy", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},

// 	{"Dragon", "Dark", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Dragon", "Steel", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Dragon", "Fairy", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},

// 	{"Dark", "Steel", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// 	{"Dark", "Fairy", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},

// 	{"Steel", "Fairy", [4]string{"Move_None", "Move_None", "Move_None", "Move_None"}},
// }